POST https://localhost:5001/api/customers/9820fca7-e9dc-414a-90a5-68692327d3db/accounts
content-type: application/json

{
  "name": "Lønnskonto"
}



###
GET https://localhost:5001/api/customers/9820fca7-e9dc-414a-90a5-68692327d3db/accounts


###
GET https://localhost:5001/api/customers/9820fca7-e9dc-414a-90a5-68692327d3db/accounts/e7bb701a-e8d1-40a6-97dc-cff805b2e03c

###
POST https://localhost:5001/api/customers/9820fca7-e9dc-414a-90a5-68692327d3db/accounts/transfer
content-type: application/json

{
  "FromAccountId": "292bec83-4e74-42dd-86fa-03982ea3e8d5",
  "ToAccountId": "e7bb701a-e8d1-40a6-97dc-cff805b2e03c",
  "Amount": "100",
}